@ECHO OFF
SETLOCAL

SET DEVROOT=D:\development

SET POPPLERROOT=%DEVROOT%\poppler
SET POPPLERPATH=%POPPLERROOT%\build\Release
SET POPPLERCPPPATH=%POPPLERROOT%\build\cpp\Release

SET PATH=%PATH%;%POPPLERPATH%;%POPPLERCPPPATH%

%~dp0\pdfhandler.exe  %*

ENDLOCAL