@ECHO OFF
SETLOCAL

SET DEVROOT=D:\development
SET POPPLERROOT=%DEVROOT%\poppler
SET POPPLERPATH=%POPPLERROOT%\build\Debug
SET POPPLERCPPPATH=%POPPLERROOT%\build\cpp\Debug

SET PATH=%PATH%;%POPPLERPATH%;%POPPLERCPPPATH%

%~dp0\pdfhandler.exe

ENDLOCAL